[window]
opacity = 0.95
padding = { x = 14, y = 14 }
dynamic_title = true
decorations = "full"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
size = 14.0      # większa, bardziej wyraźna czcionka

[colors]
primary = { background = "#1A1B26", foreground = "#C8C8F0" }
cursor = { text = "#1A1B26", cursor = "#FF9E64" }
selection = { text = "#1A1B26", background = "#7AA2F7" }

[colors.normal]
black   = "#1A1B26"
red     = "#F7768E"
green   = "#9ECE6A"
yellow  = "#E0AF68"
blue    = "#7AA2F7"
magenta = "#BB9AF7"
cyan    = "#7DCFFF"
white   = "#C0CAF5"

[colors.bright]
black   = "#414868"
red     = "#F7768E"
green   = "#9ECE6A"
yellow  = "#E0AF68"
blue    = "#7AA2F7"
magenta = "#BB9AF7"
cyan    = "#7DCFFF"
white   = "#FFFFFF"

[cursor]
style = "Beam"

[scrolling]
history = 100000    # maksymalna wartość obsługiwana
multiplier = 3
